### ISSUE TITLE
RustDesk 自建服务器搭建记录

### ISSUE THREAD

**Issue by flytam** [flytam/blog#52]
最近有个需求是希望在外网例如手机或者公司电脑连接到家里的 mac-mini

> 尝试过 TeamViewer、向日葵等软件即使不申请任何权限仅作为控制端都会被公司安全软件删除。而[RustDesk](https://github.com/rustdesk/rustdesk) 支持网页端且MAC端在不申请任何权限时也能公司电脑运行，最终采用该方案

[RustDesk](https://github.com/rustdesk/rustdesk) 是一款开源的远程桌面工具，类似 TeamViewer、向日葵等。这里基于自有的腾讯云服务器搭建自建服务远程连接家里的电脑

## 服务器配置
> 参考 https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/ ，这里使用 docker compose一键安装
```bash
mkdir -p  /root/rustdesk
cd /root/rustdesk
vim docker-compose.yaml
```
输入以下内容
```yml
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:1.4.0
    command: hbbs
    environment:
      - "RELAY=hbbr:21117"
      - "ENCRYPTED_ONLY=1"
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    volumes:
      - /root/rustdesk:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:1.4.0
    command: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    volumes:
      - /root/rustdesk/root:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

networks:
  rustdesk-net:
    external: false
```
docker 启动服务
```bash
docker compose up -d
```
启动成功

<img width="1376" alt="Image" src="https://github.com/user-attachments/assets/8d57b9a7-0672-4af5-b7ed-38d89427562e" />

记录下公钥

<img width="924" alt="Image" src="https://github.com/user-attachments/assets/78d922d0-3daf-49d4-b7d5-c2562a6460dc" />

开启云服务器相关端口

<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/bd752b6d-7fa9-4d27-a0e6-aab97fffbc54" />

## 客户端
[安装客户端](https://github.com/rustdesk/rustdesk/releases)

<img width="1112" alt="Image" src="https://github.com/user-attachments/assets/cbf5b4e1-afa8-4a38-b101-f99fedbe6b2f" />

设置网络-配置（控制端和被控端都需要填写）
- ID服务器、中继服务器填写服务器 IP
- key 填写上面的公钥地址

<img width="869" alt="Image" src="https://github.com/user-attachments/assets/015ddacd-6baf-49c5-9ced-987a311098b9" />

打开后授权各种权限。打开 2FA 使用 tg bot接收 2FA 验证码增加安全性

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/1d07fbdc-ca95-4ea4-afdc-817156d228fe" />

然后通过主页的 ID 即可连接目标电脑成功。手机或者其它电脑均可

<img width="722" alt="Image" src="https://github.com/user-attachments/assets/3f6eb2ed-4738-4f3b-a702-ee7cc07db1c0" />
